In [1]:
import numpy as np

# Question No 1

In [2]:
# Null vector of size 10
ar1 = np.array([0,0,0,0,0,0,0,0,0,0])
ar1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
ar1.size

10

In [4]:
vec2 = np.arange(10,49)
vec2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [5]:
vec2.shape

(39,)

In [6]:
vec2.dtype

dtype('int32')

In [7]:
np.version

<module 'numpy.version' from 'C:\\Users\\Bilal\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>

In [8]:
vec2.ndim

1

In [9]:
ar2 = np.array([1,2,3,4,5,6,7,8,9],  dtype=bool)
print(ar2)
# 0,non,false except all values true
# if bool == 1:
#     print("All values true")
# else:
#     print("false")

[ True  True  True  True  True  True  True  True  True]


In [10]:
ar3 = np.arange(20).reshape(5,4)
ar3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [11]:
ar3.ndim

2

In [12]:
ar4 = np.arange(64).reshape(4,4,4)
ar4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [13]:
ar4.ndim

3

In [14]:
reverse_vector =  vec2[::-1]
reverse_vector

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [15]:
emp = np.empty([3,3])
emp

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 2.03555046e-321],
       [1.05699242e-307, 3.11523242e-307, 5.68175493e-322]])

In [16]:
zero = np.zeros([10])
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
zero[4] = 1

In [18]:
zero

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [19]:
# values can be filled by using full method.
np.full([4,4],[3,4,0,8])   

array([[3, 4, 0, 8],
       [3, 4, 0, 8],
       [3, 4, 0, 8],
       [3, 4, 0, 8]])

In [20]:
idn = np.identity(3)
idn

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
ar5 = np.array([1, 2, 3, 4, 5], dtype=float)
ar5

array([1., 2., 3., 4., 5.])

In [22]:
ar5.dtype

dtype('float64')

In [23]:
ar6 = np.array([[1., 2., 3.],  [4., 5., 6.]]) 
ar7 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(ar6)
print(ar7)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 0.  4.  1.]
 [ 7.  2. 12.]]


In [24]:
ar6 * ar7

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [25]:
ar8 = np.array([[1., 2., 3.],[4., 5., 6.]]) 

ar9 = np.array([[0., 4., 1.],[7., 2., 12.]])
np.stack([ar8,ar9])

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 0.,  4.,  1.],
        [ 7.,  2., 12.]]])

In [26]:
import numpy as np
ar10 = np.array([1,2,3,4,5,6,7,8,9], dtype=int)
ar10[ar10 % 2 == 1]


array([1, 3, 5, 7, 9])

In [27]:
# replace no to -1
ar11 = np.array([1,2,3,4,5,6,7,8,9])
# a = (ar11%2 == 1)
# ar11[a] = -1
ar11[ar11 %2 == 1] = -1

In [28]:
ar11

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

In [29]:
ar12 = np.arange(10)
ar12

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
ar12[5:9] = 12

In [31]:
ar12

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [32]:
ar13 = np.ones([5,5])
print("Original array:")
print(ar13)
print("1 0n the border and 0 inside:")
ar13[1:-1, 1:-1] = 0
print(ar13)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 0n the border and 0 inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
ar14 = np.array([2,3,4,6,8,5])
print(max(2*ar14))

16


In [34]:
ar15 = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
print(ar15)
ar15[1,1] = 12
print(ar15)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


In [35]:
ar16 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(ar16)

ar16[0:1] = 64
print(ar16)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


In [36]:
ar17 = np.arange(9).reshape(3,3)
print(ar17)
print(ar17[0])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


In [37]:
ar18 = np.arange(9).reshape(3,3)
print(ar18)
print(ar18[0,1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
1


In [38]:
ar19 = np.arange(9).reshape(3,3)
print(ar19)
print(ar19[0:2, 2])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[2 5]


In [39]:
ar20 = np.arange(100).reshape(10,10)
print(ar20)
print(ar20.argmax())
print(ar20.argmin())

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
99
0


In [40]:
ar21 = np.array([1,2,3,2,3,4,3,4,5,6])
ar22 = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(ar21,ar22)

array([2, 4])

In [41]:
arr = np.random.rand(10000000)
for items in arr:
    np.where([items > 0.000034456, 1.11245, items])
print(arr)

[0.69356093 0.56392558 0.85976286 ... 0.89516075 0.70158262 0.77911036]
